name: ci

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        -
          name: Checkout
          uses: actions/checkout@v3
        -
          name: Setup Java and Maven
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '17'
            cache: 'maven'
        -
          name: Build Jar file by Maven
          run: 'mvn --batch-mode package'
        -
          name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        -
          name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v2
        -
          name: Build Docker image and push to registry
          uses: docker/build-push-action@v3
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hierarchy-exercise:latest
